version: '3.5'

services:
  postgres:
    container_name: lumi-challenge
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lumi
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
